version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      crazy-max-dot-github:
        patterns:
          - "crazy-max/.github/*"
    cooldown:
      default-days: 2
    labels:
      - "dependencies"
      - "bot"
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    versioning-strategy: "increase"
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
      - "bot"
