name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '.github/*-releases.json'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 24
          - 20
    steps:
      -
        name: Build
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7.2.0
        with:
          targets: build
        env:
          NODE_VERSION: ${{ matrix.node_version }}
